name: Java CI

on:
  push:
    branches: [ feature/pipeline ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout feature/pipeline
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Compile with Maven
        run: mvn -B clean install

      - name: Run tests
        run: mvn test
